name: Organization CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run a one-line script
        run: echo Hello, World
      
      - name: echo secret
        run: echo ${{secrets.SECRET_DEMO}}
  test-call-reusable-workflow:
    uses: workflowasis/npm-repo/.github/workflows/reusable_workflow.yml@main
    with:
      ring: mona
    secrets:
        token: ${{ secrets.TOKEN }}  
